name: "Test runner"

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  analyze:
    name: Analyze
    runs-on: ${{ matrix.os.fullname }}
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]
        os:
            - { prettyname: Windows, fullname: windows-latest, buildname: net7.0-windows10.0.19041.0 }
            - { prettyname: macOS, fullname: macos-latest, buildname: net7.0-maccatalyst }
            - { prettyname: Android, fullname: windows-latest, buildname: net7.0-android }
            - { prettyname: iOS, fullname: macos-latest, buildname: net7.0-ios }

    timeout-minutes: 60

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
        
    - name: Install dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
      
    - name: Install MAUI
      run: dotnet workload install maui

    - name: Build app
      run: dotnet build -c Debug -warnaserror -f:${{ matrix.os.buildname }} ${{github.workspace}}/PasswordManager/PasswordManager.csproj

    - name: Build tests
      run: dotnet build -c Debug -warnaserror -f:net7.0 ${{github.workspace}}/PasswordManager.Tests/PasswordManager.Tests.csproj
      
    - name: Test
      run: dotnet test --no-build --verbosity normal Passwords.sln